import os
import shutil
import numpy as np
import xarray as xr
import spatialdata as sd
import anndata as ad
from csbdeep.data import Normalizer, normalize_mi_ma
from stardist.models import StarDist2D

## VIASH START
# The following code has been auto-generated by Viash.
par = {
  'input': r'resources_test/task_spatial_segmentation/mouse_brain_combined/spatial_unlabelled.zarr',
  'output': r'resources_test/task_spatial_segmentation/mouse_brain_combined/prediction.zarr',
  'model': r'2D_versatile_fluo'
}
meta = {
  'name': r'stardist',
  'functionality_name': r'stardist',
  'resources_dir': r'/private/tmp/viash_inject_stardist15754903354685377792',
  'executable': r'/private/tmp/viash_inject_stardist15754903354685377792/stardist',
  'config': r'/private/tmp/viash_inject_stardist15754903354685377792/.config.vsh.yaml',
  'temp_dir': r'/var/folders/fq/ymt0vml175s4yvqxzbmlmpz80000gn/T/',
  'cpus': int(r'123'),
  'memory_b': int(r'123'),
  'memory_kb': int(r'123'),
  'memory_mb': int(r'123'),
  'memory_gb': int(r'123'),
  'memory_tb': int(r'123'),
  'memory_pb': int(r'123'),
  'memory_kib': int(r'123'),
  'memory_mib': int(r'123'),
  'memory_gib': int(r'123'),
  'memory_tib': int(r'123'),
  'memory_pib': int(r'123')
}
dep = {
  
}

## VIASH END


def convert_to_lower_dtype(arr):
    max_val = arr.max()
    if max_val <= np.iinfo(np.uint8).max:
        new_dtype = np.uint8
    elif max_val <= np.iinfo(np.uint16).max:
        new_dtype = np.uint16
    elif max_val <= np.iinfo(np.uint32).max:
        new_dtype = np.uint32
    else:
        new_dtype = np.uint64
    return arr.astype(new_dtype)


# Normalize per block without clipping using percentile-based min/max
class PercentileNormalizer(Normalizer):
    def __init__(self, mi, ma):
        self.mi, self.ma = mi, ma

    def before(self, x, axes):
        return normalize_mi_ma(x, self.mi, self.ma, dtype=np.float32)

    def after(self, *args, **kwargs):
        assert False

    @property
    def do_after(self):
        return False


print("Reading input", flush=True)
sdata = sd.read_zarr(par["input"])
image = sdata["morphology_mip"]["scale0"].image.compute().to_numpy()
transformation = sdata["morphology_mip"]["scale0"].image.transform.copy()

print(f"Loading pretrained StarDist model: {par['model']}", flush=True)
model = StarDist2D.from_pretrained(par["model"])

print("Running StarDist segmentation", flush=True)
mi, ma = np.percentile(image, [1, 99.8])
normalizer = PercentileNormalizer(mi, ma)
block_size = min(image.shape[1] // 3, 4096)
offset = int(min(block_size / 5.5, 128))

labels, _ = model.predict_instances_big(
    image[0, :, :],
    axes="YX",
    block_size=block_size,
    min_overlap=offset,
    context=offset,
    normalizer=normalizer,
)

print("Post-processing segmentation results", flush=True)
labels = convert_to_lower_dtype(labels)

print("Creating output data structure", flush=True)
sd_output = sd.SpatialData(
    labels={
        "segmentation": sd.models.Labels2DModel.parse(
            xr.DataArray(labels, name="segmentation", dims=("y", "x")),
            transformations=transformation,
        )
    },
    tables={
        "table": ad.AnnData(
            uns={
                "dataset_id": sdata.tables["table"].uns["dataset_id"],
                "method_id": meta["name"],
            }
        )
    },
)

print("Writing output", flush=True)
if os.path.exists(par["output"]):
    shutil.rmtree(par["output"])
sd_output.write(par["output"])
