import os
import shutil
import subprocess
from pathlib import Path
import numpy as np
import pandas as pd
import xarray as xr
import anndata as ad
import spatialdata as sd
from shapely.affinity import affine_transform as shapely_affine_transform
from spatialdata.models import Labels2DModel
from spatialdata.transformations import get_transformation
from rasterio.features import rasterize as rio_rasterize

## VIASH START
# The following code has been auto-generated by Viash.
par = {
  'input': r'resources_test/task_spatial_segmentation/mouse_brain_combined/spatial_unlabelled.zarr',
  'output': r'resources_test/task_spatial_segmentation/mouse_brain_combined/prediction.zarr',
  'voxel_layers': int(r'4'),
  'samples': int(r'200'),
  'burnin_samples': int(r'200'),
  'voxel_size': float(r'1.0'),
  'burnin_voxel_size': float(r'2.0')
}
meta = {
  'name': r'proseg',
  'functionality_name': r'proseg',
  'resources_dir': r'/private/tmp/viash_inject_proseg11113472565944867086',
  'executable': r'/private/tmp/viash_inject_proseg11113472565944867086/proseg',
  'config': r'/private/tmp/viash_inject_proseg11113472565944867086/.config.vsh.yaml',
  'temp_dir': r'/var/folders/fq/ymt0vml175s4yvqxzbmlmpz80000gn/T/',
  'cpus': int(r'123'),
  'memory_b': int(r'123'),
  'memory_kb': int(r'123'),
  'memory_mb': int(r'123'),
  'memory_gb': int(r'123'),
  'memory_tb': int(r'123'),
  'memory_pb': int(r'123'),
  'memory_kib': int(r'123'),
  'memory_mib': int(r'123'),
  'memory_gib': int(r'123'),
  'memory_tib': int(r'123'),
  'memory_pib': int(r'123')
}
dep = {

}

## VIASH END

proseg_dir = Path(meta['temp_dir'] or '/tmp') / 'proseg'
proseg_dir.mkdir(parents=True, exist_ok=True)

print('Reading input', flush=True)
sdata = sd.read_zarr(par['input'])
image = sdata['morphology_mip']['scale0'].image.compute().to_numpy()
transformation = sdata['morphology_mip']['scale0'].image.transform.copy()
h, w = image.shape[-2:]

print('Exporting transcripts to CSV', flush=True)
transcripts_df = sdata['transcripts'].compute()
has_z = 'z' in transcripts_df.columns and transcripts_df['z'].notna().any()

# Proseg requires a prior cell-ID column. Build a simple grid-based prior so
# proseg can refine the segmentation from a meaningful starting state.
x_min, x_max = float(transcripts_df['x'].min()), float(transcripts_df['x'].max())
y_min, y_max = float(transcripts_df['y'].min()), float(transcripts_df['y'].max())
grid_size = 20.0  # microns per grid cell — roughly one cell diameter
x_bins = np.arange(x_min, x_max + grid_size, grid_size)
y_bins = np.arange(y_min, y_max + grid_size, grid_size)
x_idx = np.digitize(transcripts_df['x'].to_numpy(), x_bins) - 1
y_idx = np.digitize(transcripts_df['y'].to_numpy(), y_bins) - 1
n_x = max(len(x_bins) - 1, 1)
prior_cell_ids = (y_idx * n_x + x_idx) + 1  # 1-indexed; 0 is "unassigned"

z_vals = transcripts_df['z'] if has_z else np.zeros(len(transcripts_df))
csv_data = {
    'x': transcripts_df['x'],
    'y': transcripts_df['y'],
    'z': z_vals,
    'gene': transcripts_df['feature_name'],
    'cell_id': prior_cell_ids,
}
transcript_csv = proseg_dir / 'transcripts.csv'
pd.DataFrame(csv_data).to_csv(transcript_csv, index=False)

n_threads = max((meta.get('cpus') or os.cpu_count() or 1) - 2, 1)
cmd = [
    'proseg', 'transcripts.csv',
    '--x-column', 'x',
    '--y-column', 'y',
    '--z-column', 'z',
    '--gene-column', 'gene',
    '--cell-id-column', 'cell_id',
    '--cell-id-unassigned', '0',
    '--nthreads', str(n_threads),
    '--ncomponents', '10',
    '--diffusion-probability', '0.2',
    '--diffusion-sigma-far', '4',
    '--diffusion-sigma-near', '1',
    '--nuclear-reassignment-prob', '0.2',
    '--cell-compactness', '0.03',
    '--voxel-layers', str(par['voxel_layers']),
    '--samples', str(par['samples']),
    '--burnin-samples', str(par['burnin_samples']),
    '--recorded-samples', str(par['samples']),
    '--voxel-size', str(par['voxel_size']),
    '--burnin-voxel-size', str(par['burnin_voxel_size']),
]
print(f'Running Proseg: {" ".join(cmd)}', flush=True)
subprocess.run(cmd, cwd=str(proseg_dir), check=True)

print('Reading Proseg Zarr output', flush=True)
proseg_sdata = sd.read_zarr(str(proseg_dir / 'proseg-output.zarr'))
shapes = proseg_sdata.shapes['cell_boundaries']
print(f'Found {len(shapes)} cell boundaries', flush=True)

# Proseg boundaries are in global (micron) coordinates. Convert to pixel space
# using the inverse of the morphology image's pixel-to-global transformation.
print('Converting boundaries to pixel space and rasterizing', flush=True)
img_transform = get_transformation(sdata['morphology_mip'], to_coordinate_system='global')
affine_mat = img_transform.to_affine_matrix(input_axes=('x', 'y'), output_axes=('x', 'y'))
inv_affine = np.linalg.inv(affine_mat)

def global_to_pixel(geom):
    a, b, xoff = inv_affine[0, 0], inv_affine[0, 1], inv_affine[0, 2]
    d, e, yoff = inv_affine[1, 0], inv_affine[1, 1], inv_affine[1, 2]
    return shapely_affine_transform(geom, [a, b, d, e, xoff, yoff])

pixel_geoms = shapes['geometry'].apply(global_to_pixel)
shape_geoms = list(zip(pixel_geoms, range(1, len(shapes) + 1)))
labels = rio_rasterize(shape_geoms, out_shape=(h, w), fill=0, dtype=np.int32)

max_val = labels.max()
if max_val <= np.iinfo(np.uint8).max:
    labels = labels.astype(np.uint8)
elif max_val <= np.iinfo(np.uint16).max:
    labels = labels.astype(np.uint16)
elif max_val <= np.iinfo(np.uint32).max:
    labels = labels.astype(np.uint32)

print('Creating output data structure', flush=True)
sd_output = sd.SpatialData(
    labels={
        'segmentation': Labels2DModel.parse(
            xr.DataArray(labels, name='segmentation', dims=('y', 'x')),
            transformations=transformation,
        )
    },
    tables={
        'table': ad.AnnData(
            uns={
                'dataset_id': sdata.tables['table'].uns['dataset_id'],
                'method_id': meta['name'],
            }
        )
    },
)

print('Writing output', flush=True)
if os.path.exists(par['output']):
    shutil.rmtree(par['output'])
sd_output.write(par['output'])
