#!/bin/bash

# get the root of the directory
REPO_ROOT=$(git rev-parse --show-toplevel)

# ensure that the command below is run from the root of the repository
cd "$REPO_ROOT"

set -e

if [ ! -d resources_test/task_spatial_segmentation/mouse_brain_combined ]; then
  mkdir -p resources_test/task_spatial_segmentation/mouse_brain_combined
fi

# these files were generated by https://github.com/openproblems-bio/task_ist_preprocessing/tree/main/scripts/create_test_resources
# we can just copy them for now

aws s3 sync --profile op \
  s3://openproblems-data/resources_test/task_ist_preprocessing/mouse_brain_combined/raw_ist.zarr \
  resources_test/task_spatial_segmentation/mouse_brain_combined/raw_ist.zarr

aws s3 cp --profile op \
  s3://openproblems-data/resources_test/task_ist_preprocessing/mouse_brain_combined/scrnaseq_reference.h5ad \
  resources_test/task_spatial_segmentation/mouse_brain_combined/scrnaseq_reference.h5ad

# ...additional preprocessing if needed ...

# sync to s3
aws s3 sync --profile op \
  "resources_test/task_spatial_segmentation/mouse_brain_combined/" \
  "s3://openproblems-data/resources_test/task_spatial_segmentation/mouse_brain_combined/" \
  --delete --dryrun
