__merge__: /src/api/comp_dataset_loader_tenx_xenium.yaml

name: tenx_xenium

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi:
          - spatialdata-io
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midmem, midcpu, midtime]